### ISSUE TITLE
HysteresisLogic  Heating and Cooling function 

### ISSUE THREAD

**Issue by ChuckGl** [hrafnkelle/tfbrew#2]
I am trying to reconfigure my tfbrew to use the new HysteresisLogic  setup for heating and cooling.  I don't get any errors when starting tfbrew but the heating in always on regardless of temp and setpoint.  I am using a TPLink for Cooling (1.1.1.1) and a separate TPLink for Heating(1.1.1.2).  This is what my config.yaml looks like.
actors:
  - Cooling:
     plugin: TPLinkActor
     ip: 1.1.1.1
  - Heating:
     plugin: TPLinkActor
     ip: 1.1.1.2

controllers:
  - FermentationCooling:
      plugin: HysteresisLogic
      keepCold: True
      logicCoeffs:
        allowedOvershoot: 0.1
        allowedUndershoot: 0.0
      actor: Cooling
      sensor: Tilt
      initialSetpoint: 18
      initialState: on
  - FermentationHeating:
      plugin: HysteresisLogic
      keepHot: True
      logicCoeffs:
        allowedOvershoot: 0.1
        allowedUndershoot: 0.0
      actor: Heating
      sensor: Tilt
      initialSetpoint: 17
      initialState: on

**Comment by hrafnkelle** [comment]
You need to have the keepHot/keepCold parameters under logicCoeffs, just like allowedOvershoot/allowedUndershoot. Otherwise the HysteresisLogic plugin doesn't see them and just assumes default, that is to cool. I also spotted a minor bug in the reading of the keepCold/Hot parameters thanks to you but that bug shouldn't affect you. Still reccomend you pull the latest updates, fix your config.yaml and try again. Please report back.

**Comment by ChuckGl** [comment]
That got it thanks.  I also see the keepHeat is in the instructions now.
That will surely help others.

**Comment by hrafnkelle** [comment]
Great. Closing this issue then. Yes I updated the documentation.

Thanks for taking the time to report issues so I can fix them.
